### ISSUE TITLE
请教二维码扫描的可以准确识别DM格式

### ISSUE THREAD

**Issue by DDjason** [damonfu/PrivacyPolicy#1]
请教二维码扫描的可以准确识别DM格式，我尝试了很多Zxing的库，和并让扫码支持DM格式的二维码，但是识别不了，请问你的是使用什么库或者怎么实现的，

**Comment by DDjason** [comment]
![微信图片_20210119075643](https://user-images.githubusercontent.com/16483208/104972657-56218e80-5a2d-11eb-8172-7466e8f8b264.png)

**Comment by damonfu** [comment]
非开源项目优化，无法帮助上你，抱歉。



---原始邮件---
发件人: "DDjason"<notifications@github.com&gt;
发送时间: 2021年1月19日(周二) 上午9:21
收件人: "damonfu/PrivacyPolicy"<PrivacyPolicy@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [damonfu/PrivacyPolicy] 请教二维码扫描的可以准确识别DM格式 (#1)




 
请教二维码扫描的可以准确识别DM格式，我尝试了很多Zxing的库，和并让扫码支持DM格式的二维码，但是识别不了，请问你的是使用什么库或者怎么实现的，
